### ISSUE TITLE
Rename to npm-mem-fs

### ISSUE THREAD

**Issue by felixfbecker** [types/mem-fs#1]

**Comment by unional** [comment]
We are debating should we change to this scheme so that it matched `@types/*` format.

So now I'm creating these repo with these names.

**Comment by unional** [comment]
Reference:
https://github.com/Microsoft/types-publisher/issues/108

**Comment by felixfbecker** [comment]
Thanks for linking.

**Comment by unional** [comment]
No problem. Thanks for being on top of things! 🌷
